// SPDX-License-Identifier: Apache-2.0

export const studioContract = {
  controls: [
    "Bootstrap token",
    "Descriptive Profile",
    "Authoritative Mandate",
    "Revisioned colleague builder",
    "Typed policy",
    "Explicit defaults",
    "Review exact revision",
    "Confirm exact revision & digest",
    "Cancel draft",
    "Finite work",
    "Wake-cycle inspector",
    "Proposal inbox",
    "Approve exact revision",
    "Reject exact revision",
    "Causal audit",
    "ACTIONRESULT",
  ],
  states: [
    "loading",
    "empty",
    "success",
    "validation",
    "permission",
    "rejection",
    "stale",
    "conflict",
    "cancelled",
    "error",
  ],
  diffClassifications: [
    "added",
    "removed",
    "changed",
    "narrowed",
    "expanded",
    "unchanged",
  ],
} as const;
