// SPDX-License-Identifier: Apache-2.0

import type { TranslationKey } from "./locales/en-US";

export const studioContract: {
  controls: TranslationKey[];
  states: string[];
  diffClassifications: string[];
} = {
  controls: [
    "bootstrap.token",
    "builder.profile_kicker",
    "builder.mandate_kicker",
    "revision.kicker",
    "revision.typed_policy",
    "revision.defaults",
    "builder.review_exact",
    "revision.confirm_digest",
    "revision.cancel",
    "work.kicker",
    "wake.kicker",
    "proposal.kicker",
    "proposal.approve",
    "proposal.reject",
    "audit.kicker",
    "governance.kicker",
    "governance.session_binding",
    "governance.no_credentials",
    "governance.authorize_recovery",
    "governance.credentials",
    "governance.pending_changes",
    "governance.reviewed_diff_aria",
    "governance.separate_admin",
    "nav.aria",
    "governance.safe_export",
    "audit.result_stamp",
    "nav.registry",
    "registry.validate",
    "registry.trust",
    "registry.revoke",
    "registry.install",
    "registry.register",
    "registry.create_draft",
    "registry.select_capabilities",
    "registry.confirm_extra",
    "registry.review",
    "registry.confirm",
    "registry.activate",
    "registry.pause",
    "registry.block",
    "registry.retire",
    "registry.upgrade",
    "registry.rollback",
    "registry.select",
    "registry.audit",
    "registry.drafts",
    "registry.provenance",
    "registry.verification_result",
    "registry.signer_digest",
    "registry.attestation_origin_only",
    "registry.trust_independent",
    "registry.authority_unbound",
  ],
  states: [
    "loading",
    "empty",
    "success",
    "validation",
    "permission",
    "rejection",
    "stale",
    "conflict",
    "cancelled",
    "error",
    "expired",
    "revoked",
    "read-only",
  ],
  diffClassifications: [
    "added",
    "removed",
    "changed",
    "narrowed",
    "expanded",
    "unchanged",
  ],
};
