// SPDX-License-Identifier: Apache-2.0

export const studioContract = {
  controls: [
    "Bootstrap token",
    "Descriptive Profile",
    "Authoritative Mandate",
    "Revisioned colleague builder",
    "Typed policy",
    "Explicit defaults",
    "Review exact revision",
    "Confirm exact revision & digest",
    "Cancel draft",
    "Finite work",
    "Wake-cycle inspector",
    "Proposal inbox",
    "Approve exact revision",
    "Reject exact revision",
    "Causal audit",
    "Governance & access",
    "Session role and membership revision",
    "Enrollment status without plaintext",
    "Recovery status without plaintext",
    "Credential lifecycle status",
    "Pending exact change approval",
    "Reviewed exact change diff",
    "Separate proposer and approver",
    "Role-filtered navigation",
    "Bounded safe audit export",
    "ACTIONRESULT",
  ],
  states: [
    "loading",
    "empty",
    "success",
    "validation",
    "permission",
    "rejection",
    "stale",
    "conflict",
    "cancelled",
    "error",
    "expired",
    "revoked",
    "read-only",
  ],
  diffClassifications: [
    "added",
    "removed",
    "changed",
    "narrowed",
    "expanded",
    "unchanged",
  ],
} as const;
